<style>
    @font-face{font-family:"Vazirmatn";src:url("{{ asset('fonts/Vazirmatn.woff2') }}") format("woff2");font-style:normal;font-weight:100 900;font-display:swap}
    :root{--ink:#18302b;--muted:#667873;--cream:#f6f2e9;--paper:#fffdf8;--green:#126b56;--green2:#0b4e40;--orange:#ec7b38;--line:#dfe5df;--shadow:0 18px 50px rgba(26,52,45,.1)}
    *{box-sizing:border-box}html{background:var(--paper)}body{margin:0;background:var(--paper);color:var(--ink);font-family:"Vazirmatn",Tahoma,sans-serif;line-height:1.8}a{color:inherit;text-decoration:none}button,input,textarea,select{font:inherit}[hidden]{display:none!important}.container{width:min(1160px,calc(100% - 32px));margin-inline:auto}
    .site-header{height:76px;background:rgba(255,253,248,.94);border-bottom:1px solid var(--line);display:flex;align-items:center;position:sticky;top:0;z-index:20;backdrop-filter:blur(14px)}.nav-wrap{display:flex;align-items:center;justify-content:space-between}.header-branding{display:flex;align-items:center;flex-shrink:0}.brand{display:flex;align-items:center;gap:10px;font-size:25px;font-weight:800}.brand-logo-mark{position:relative;width:58px;height:58px;flex:0 0 58px;overflow:hidden}.brand-logo-mark img{position:absolute;top:0;right:0;width:auto;max-width:none;height:58px}.brand-copy{display:flex;flex-direction:column;justify-content:center;min-width:0}.brand-name{font-size:25px;font-weight:900;line-height:1.15}.brand .brand-name>span{color:var(--orange)}.header-slogan{max-width:180px;margin-top:3px;color:var(--muted);font-size:9px;font-weight:650;line-height:1.45}
    nav{display:flex;align-items:center;gap:25px;font-size:14px;font-weight:600}.inline-form{display:inline}.link-button{border:0;background:none;color:inherit;padding:0}.header-search{position:relative;width:min(360px,32vw);margin-inline:auto 22px}.header-search form{display:flex;position:relative}.header-search input{width:100%;height:40px;margin:0;padding:7px 13px 7px 42px;border:1px solid #cfd9d4;border-radius:20px;background:#f7f8f5}.header-search button{position:absolute;left:4px;top:4px;width:32px;height:32px;border:0;border-radius:50%;background:var(--green);color:#fff}
    .hero{min-height:440px;overflow:hidden;position:relative;background:var(--cream)}.hero-content{display:flex;align-items:center;justify-content:space-between;min-height:440px;position:relative}.hero h1{margin:10px 0 18px;font-size:58px;line-height:1.35;letter-spacing:-2px}.hero p{max-width:620px;color:var(--muted);font-size:17px}.hero-orbit{width:250px;height:250px;border:1px dashed #9db0a8;border-radius:50%;display:grid;place-items:center}.eyebrow{color:var(--orange);font-size:13px;font-weight:800}.tour-hero{height:390px;position:relative;overflow:hidden;background:var(--green2);color:#fff}.tour-hero>img{position:absolute;width:100%;height:100%;object-fit:cover}.tour-hero-overlay{position:absolute;inset:0;background:linear-gradient(90deg,rgba(5,40,33,.25),rgba(5,40,33,.88))}.tour-hero-content{position:relative;height:100%;display:flex;flex-direction:column;justify-content:center}.tour-hero h1{margin:25px 0 5px;font-size:52px}.provider-hero{padding:55px 0;background:linear-gradient(135deg,var(--cream),#e8f2ed)}.provider-hero-content{display:flex;align-items:center;gap:26px}.static-page{width:min(900px,calc(100% - 32px));padding-block:60px;min-height:60vh}.static-page-head h1{margin:5px 0;font-size:42px}.panel{background:#fff;border:1px solid var(--line);border-radius:16px}.admin-page{padding-block:50px;min-height:70vh}
    .section-space{padding-block:70px}.section-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:28px}.tour-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}.tour-card{overflow:hidden;border:1px solid var(--line);border-radius:18px;background:#fff}.tour-card-link{display:flex;height:100%;flex-direction:column}.card-image{position:relative;display:block;height:230px;overflow:hidden;background:#e5ece7}.card-image img{display:block;width:100%;height:100%;object-fit:cover}.card-body{flex:1}
    @media(max-width:900px){.nav-wrap{flex-wrap:wrap;padding-block:10px}.site-header{height:auto;min-height:76px}.header-search{order:3;width:100%;margin:9px 0 0}.hero-orbit{display:none}.hero h1{font-size:45px}.tour-grid{grid-template-columns:repeat(2,1fr)}}
    @media(max-width:620px){.nav-wrap{padding-block:7px}.header-branding{order:1;width:100%}.brand-logo-mark{width:45px;height:45px;flex-basis:45px}.brand-logo-mark img{height:45px}.brand-name{font-size:22px}.header-slogan{max-width:none;font-size:8.5px;white-space:nowrap}.header-search{order:2;margin-top:7px}.nav-wrap>nav{order:3;width:100%;margin-top:6px;overflow-x:auto;white-space:nowrap}.hero,.hero-content{min-height:390px}.hero h1,.tour-hero h1{font-size:37px}.tour-hero{height:320px}.tour-grid{grid-template-columns:1fr}}
</style>
