<?php

return [
    'user_agent' => env('CRAWLER_USER_AGENT', 'Mozilla/5.0 (compatible; TourCompareBot/1.0; +'.env('APP_URL').')'),
    'search_days' => (int) env('CRAWLER_SEARCH_DAYS', 30),
    'safarmarket_origin_id' => (int) env('SAFARMARKET_ORIGIN_ID', 19981),
    'trends_geo' => env('GOOGLE_TRENDS_GEO', 'IR'),
    'trends_feed_url' => env('GOOGLE_TRENDS_FEED_URL', 'https://trends.google.com/trending/rss'),
    'suggestions_limit' => (int) env('TOUR_SUGGESTIONS_LIMIT', 120),
    'images' => [
        'api_url' => env('TOUR_IMAGE_API_URL', 'https://commons.wikimedia.org/w/api.php'),
        'count' => (int) env('TOUR_IMAGE_COUNT', 4),
        'search_limit' => (int) env('TOUR_IMAGE_SEARCH_LIMIT', 20),
        'download_width' => (int) env('TOUR_IMAGE_DOWNLOAD_WIDTH', 1920),
        'min_width' => (int) env('TOUR_IMAGE_MIN_WIDTH', 1280),
        'min_height' => (int) env('TOUR_IMAGE_MIN_HEIGHT', 720),
        'min_aspect_ratio' => (float) env('TOUR_IMAGE_MIN_ASPECT_RATIO', 1.2),
        'max_bytes' => (int) env('TOUR_IMAGE_MAX_BYTES', 8_388_608),
        'aliases' => [
            'کیش' => 'Kish Island Iran',
            'مشهد' => 'Mashhad Iran',
            'قشم' => 'Qeshm Island Iran',
            'شیراز' => 'Shiraz Iran',
            'اصفهان' => 'Isfahan Iran',
            'یزد' => 'Yazd Iran',
            'تبریز' => 'Tabriz Iran',
            'چابهار' => 'Chabahar Iran',
            'رشت' => 'Rasht Iran',
            'ماسال' => 'Masal Gilan Iran',
            'رامسر' => 'Ramsar Iran',
            'لاهیجان' => 'Lahijan Iran',
            'بندر انزلی' => 'Bandar Anzali Iran',
            'اردبیل' => 'Ardabil Iran',
            'سرعین' => 'Sareyn Iran',
            'همدان' => 'Hamadan Iran',
            'کرمان' => 'Kerman Iran',
            'کرمانشاه' => 'Kermanshah Iran',
            'سنندج' => 'Sanandaj Iran',
            'مریوان' => 'Marivan Iran',
            'اهواز' => 'Ahvaz Iran',
            'شوشتر' => 'Shushtar Iran',
            'بوشهر' => 'Bushehr Iran',
            'بندرعباس' => 'Bandar Abbas Iran',
            'جزیره هرمز' => 'Hormuz Island Iran',
            'لرستان' => 'Lorestan Iran',
            'خرم‌آباد' => 'Khorramabad Iran',
            'کاشان' => 'Kashan Iran',
            'تهران' => 'Tehran Iran',
            'دماوند' => 'Mount Damavand Iran',
            'مازندران' => 'Mazandaran Iran',
            'گیلان' => 'Gilan Iran',
            'کویر مرنجاب' => 'Maranjab Desert Iran',
            'طبس' => 'Tabas Iran',
            'کلاردشت' => 'Kelardasht Iran',
            'نمک‌آبرود' => 'Namak Abrud Iran',
            'استانبول' => 'Istanbul Turkey',
            'دبی' => 'Dubai United Arab Emirates',
            'آنتالیا' => 'Antalya Turkey',
            'تفلیس' => 'Tbilisi Georgia',
            'باتومی' => 'Batumi Georgia',
            'وان' => 'Van Turkey',
            'باکو' => 'Baku Azerbaijan',
            'ارمنستان' => 'Armenia',
            'ایروان' => 'Yerevan Armenia',
            'تایلند' => 'Thailand',
            'پوکت' => 'Phuket Thailand',
            'پاتایا' => 'Pattaya Thailand',
            'بانکوک' => 'Bangkok Thailand',
            'بالی' => 'Bali Indonesia',
            'مالدیو' => 'Maldives',
            'روسیه' => 'Russia travel',
            'مسکو' => 'Moscow Russia',
            'سنت پترزبورگ' => 'Saint Petersburg Russia',
            'گرجستان' => 'Georgia country travel',
            'ترکیه' => 'Turkey travel',
            'عمان' => 'Oman travel',
            'مسقط' => 'Muscat Oman',
            'قطر' => 'Qatar travel',
            'دوحه' => 'Doha Qatar',
            'چین' => 'China travel',
            'پکن' => 'Beijing China',
            'شانگهای' => 'Shanghai China',
            'ژاپن' => 'Japan travel',
            'توکیو' => 'Tokyo Japan',
            'هند' => 'India travel',
            'گوا' => 'Goa India',
            'دهلی' => 'Delhi India',
            'سریلانکا' => 'Sri Lanka travel',
            'مالزی' => 'Malaysia travel',
            'کوالالامپور' => 'Kuala Lumpur Malaysia',
            'سنگاپور' => 'Singapore city',
            'ویتنام' => 'Vietnam travel',
            'آفریقای جنوبی' => 'South Africa travel',
            'زنگبار' => 'Zanzibar Tanzania',
            'کنیا' => 'Kenya travel',
            'مصر' => 'Egypt travel',
            'فرانسه' => 'France travel',
            'پاریس' => 'Paris France',
            'ایتالیا' => 'Italy travel',
            'رم' => 'Rome Italy',
            'اسپانیا' => 'Spain travel',
            'بارسلونا' => 'Barcelona Spain',
            'سوئیس' => 'Switzerland travel',
            'اتریش' => 'Austria travel',
            'آلمان' => 'Germany travel',
            'هلند' => 'Netherlands travel',
            'یونان' => 'Greece travel',
            'آتن' => 'Athens Greece',
            'قبرس' => 'Cyprus travel',
            'لارناکا' => 'Larnaca Cyprus',
            'برزیل' => 'Brazil travel',
            'ریودوژانیرو' => 'Rio de Janeiro Brazil',
            'موریس' => 'Mauritius island',
            'سیشل' => 'Seychelles islands',
            'اندونزی' => 'Indonesia travel',
            'ازبکستان' => 'Uzbekistan travel',
            'سمرقند' => 'Samarkand Uzbekistan',
            'قزاقستان' => 'Kazakhstan travel',
            'آلماتی' => 'Almaty Kazakhstan',
            'قرقیزستان' => 'Kyrgyzstan travel',
            'لبنان' => 'Lebanon travel',
            'بیروت' => 'Beirut Lebanon',
        ],
    ],
    'providers' => [
        ['name' => 'علی‌بابا', 'type' => 'alibaba', 'url' => 'https://www.alibaba.ir/tour'],
        ['name' => 'فلای‌تودی', 'type' => 'flytoday', 'url' => 'https://www.flytoday.ir/packagetour'],
        ['name' => 'سفرمارکت', 'type' => 'safarmarket', 'url' => 'https://safarmarket.com/tours'],
        ['name' => 'اقامت ۲۴', 'type' => 'marketplace_html', 'url' => 'https://www.eghamat24.com/Tours.html'],
        ['name' => 'لحظه آخر', 'type' => 'marketplace_html', 'url' => 'https://lahzeakhar.com/tour'],
        ['name' => 'لست‌سکند', 'type' => 'marketplace_html', 'url' => 'https://lastsecond.ir/tours'],
        ['name' => 'نهال‌گشت', 'type' => 'marketplace_html', 'url' => 'https://nahalgasht.com/tours/'],
        ['name' => 'مقتدر سیر', 'type' => 'marketplace_html', 'url' => 'https://mstiran.com/'],
        ['name' => 'جیمبو', 'type' => 'marketplace_html', 'url' => 'https://www.jimbo.ir/tours/'],
        ['name' => 'امین', 'type' => 'marketplace_html', 'url' => 'https://amenin.co/'],
    ],
];
